Hebrew transaltion -  2.3.1.0 Support
rcmaehl/WhyNotWin11 pull request #480
Opened 2021-07-11 17:41 UTC by HypeGameMode

Added Hebrew translation for the newer update 2.3.1.0

2021-07-12 08:18 UTC, micwoj92 commented
@dinuto Do you agree with these translations?

2021-07-12 17:00 UTC, dinuto requested changes

2021-07-12 18:15 UTC, HypeGameMode commented
That's good for me.
You can merge it

2021-07-13 02:47 UTC, micwoj92 commented
> That's good for me.
> You can merge it

Merge now? There is mistake, for example in lines 69-70.

2021-07-13 15:52 UTC, dinuto commented
I think you have to manually add the changes I suggested (if you agree to them, of course).
<div dir="rtl">סורי על הסיבוך, גם אני חשבתי שאפשר פשוט לאשר את ההצעות והן יתווספו אוטומטית...</div>

2021-07-13 15:57 UTC, HypeGameMode commented
> 
> 
> > That's good for me.
> > You can merge it
> 
> Merge now? There is mistake, for example in lines 69-70.

Take all @dinuto requests and then merge it.
He fixed some mistakes I did in the translation, so it's good enough what he did

2021-07-13 18:08 UTC, micwoj92 commented
Ok, I will do that now. You marked these as resolved so I didn't exactly know what you meant :/

2021-07-13 18:11 UTC, micwoj92 commented on Langs/040D.lang
> +רמת הפיטצ'רים שהכרטיס מסך תומך/DirectX-רמת ה
So this line should be deleted? That's last thing to check before merging.

2021-07-13 18:24 UTC, dinuto commented on Langs/040D.lang
> +רמת הפיטצ'רים שהכרטיס מסך תומך/DirectX-רמת ה
Yes, thank you!

2021-07-13 20:45 UTC, merged