update zh-cn
rcmaehl/WhyNotWin11 pull request #537
Opened 2021-07-26 14:05 UTC by BluesDawn576

2021-07-26 14:34 UTC, micwoj92 commented
@chenyiping1995 do you approve these?

2021-07-26 16:06 UTC, chenyiping1995 commented on Langs/0804.lang
> +Listed as Compatible=符合系统要求
I dont think translations for line 41 and 42 convey the original meaning.

*Not on the compatible list* does not necessarily mean *incompatible* or *not meeting system requirement*. It is the user's judgment after all.

You can't plain tell the users that their machine does not meet the system requirements, just becauae their CPU is *not listed as compatible*.

I'd suggest keeping the original translation for line 41 to 42.

2021-07-26 16:09 UTC, chenyiping1995 commented on Langs/0804.lang
> +TPM=指 Windows 使用的安全模块。所有新款 AMD CPU 自带此模块，部分新款 Intel CPU 自带。请检查主板中的 BIOS/UEFI 设置，具体请参阅您的主板使用手册。
Haven't got the chance to read the original text to the descriptions section yet. I will do that in the coming morning.

2021-07-27 02:01 UTC, chenyiping1995 requested changes
Description section has been reviewed, and a few changes have been proposed.

2021-07-27 02:01 UTC, chenyiping1995 commented on Langs/0804.lang
> +Storage=指磁盘中数据可使用的空间量。有些高端笔记本电脑可以更换或升级。
指磁盘中可用于存储数据的容量。高端笔记本电脑可以更换或升级。

2021-07-27 02:01 UTC, chenyiping1995 commented on Langs/0804.lang
> +TPM=指 Windows 使用的安全模块。所有新款 AMD CPU 自带此模块，部分新款 Intel CPU 自带。请检查主板中的 BIOS/UEFI 设置，具体请参阅您的主板使用手册。
指 Windows 使用的安全模块。所有现代 AMD 处理器和一部分现代 Intel 处理器自带此模块。请检查主板中的 BIOS/UEFI 设置。具体请参阅您的主板使用手册。

2021-07-27 02:30 UTC, BluesDawn576 commented
@chenyiping1995 ok

2021-07-27 10:38 UTC, chenyiping1995 commented
@micwoj92 I don't have anything else to comment. You can merge these if you want to.

2021-07-27 15:19 UTC, merged