Improved Slovenian and Hungarian translations
rcmaehl/WhyNotWin11 pull request #739
Opened 2024-01-18 17:58 UTC by ExtremePro11299

Please describe your feature/changes on this pull:
Changed small things in Hungarian. Shortened strings in Slovenian because they were not visible.
The "Your Windows 11 compatibility results are below" string is still too long - I haven't touched it.

When I set it to Slovenian, the updated language did not show up though, you may request changes or fix it yourself (I allow edits by maintainers)

I haven't checked Hungarian yet, but I think it has the same problem.

- [ ] Make updated Slovenian show up
- [ ] Make updated Hungarian show up

2024-01-20 19:12 UTC, ExtremePro11299 commented
Also closes #726.

2024-01-29 18:13 UTC, rcmaehl requested changes
&& has to be left in until it's modified in the application to look for that string. Please revert. Otherwise LGTM

2024-01-30 15:51 UTC, ExtremePro11299 commented
Done.

2024-01-30 16:49 UTC, rcmaehl approved these changes

2024-01-30 16:50 UTC, merged